# Generated by Django 4.0.5 on 2022-06-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_gender_gender_alter_name_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
