# Generated by Django 4.0.5 on 2022-06-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_alter_name_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='gender',
            name='name',
        ),
        migrations.DeleteModel(
            name='age',
        ),
        migrations.DeleteModel(
            name='gender',
        ),
        migrations.DeleteModel(
            name='name',
        ),
    ]
